-- AlterTable
ALTER TABLE `QrCode` ADD COLUMN `logoSize` INTEGER NOT NULL DEFAULT 20,
    ADD COLUMN `margin` INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN `type` ENUM('URL', 'TEXT', 'EMAIL', 'WIFI', 'VCARD', 'SMS', 'PHONE', 'LOCATION', 'BITCOIN') NOT NULL DEFAULT 'TEXT';
