-- AlterTable
ALTER TABLE `QrCode` ADD COLUMN `finderFrameStyle` ENUM('SQUARE', 'ROUNDED', 'CIRCLE') NOT NULL DEFAULT 'SQUARE',
    ADD COLUMN `finderMarkerStyle` ENUM('SQUARE', 'ROUNDED', 'CIRCLE') NOT NULL DEFAULT 'SQUARE';
